apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: backend
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:postgresql://10.106.127.74:5432/taskmanager
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: postgres123
