apiVersion: v1
kind: Service
metadata:
  name: task-manager
  namespace: backend
spec:
  type: NodePort
  selector:
    app: task-manager
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
